---
- name: Hello World Playbook
  hosts: all
  gather_facts: no  # 先改回 no
  tasks:
    - name: Print hello message
      debug:
        msg: "Hello from AWX!"
    
    - name: Create a test file
      shell: "echo 'AWX test successful at $(date)' > /tmp/awx_test.txt"
      become: yes

    - name: Cat test file content
      shell: "cat /tmp/awx_test.txt"
      register: file_content

    - name: Show file content
      debug:
        var: file_content.stdout
